stages:
  - build
  - deploy

# Staging
gcp-build-staging:
  image: google/cloud-sdk:alpine
  stage: build
  only:
    - staging
  script:
    - echo $GCP_SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - export GCR_TAG=gcr.io/$CI_PROJECT_NAME
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud builds submit --config ".gcp-build-staging.yaml" --project=$PROJECT_ID

gcp-deploy-staging:
  image: google/cloud-sdk:alpine
  stage: deploy
  only:
    - staging
  script:
    - echo $GCP_SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - export GCR_TAG=gcr.io/$CI_PROJECT_NAME
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID compute instances reset front-end-staging --zone=us-central1-a

# Production
gcp-build-prod:
  image: google/cloud-sdk:alpine
  stage: build
  only:
    - master
  script:
    - echo $GCP_SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - export GCR_TAG=gcr.io/$CI_PROJECT_NAME
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud builds submit --config ".gcp-build-prod.yaml" --project=$PROJECT_ID

gcp-deploy-prod:
  image: google/cloud-sdk:alpine
  stage: deploy
  only:
    - master
  script:
    - echo $GCP_SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - export GCR_TAG=gcr.io/$CI_PROJECT_NAME
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID compute instances reset front-end-prod --zone=us-central1-a